site_name: Plataforma Cognitiva

# Tema Material para MkDocs
# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  language: en
  features:
    - navigation.expand

nav:
  - Guia de implementação:
      - Overview: index.md
      - Tutorials:
          - "Como criar EC2 Ubuntu": implementation-guide/tutorials/criar-ec2.md
          - "Como criar RDS PostgreSQL com pgvector": implementation-guide/tutorials/criar-RDS.md
          - "Como criar Bucket S3": implementation-guide/tutorials/criar-s3.md
          - "Como criar site no S3 e CloudFront": implementation-guide/tutorials/criar-site.md
          - "Como conectar o ec2 no RDS": implementation-guide/tutorials/conectar-ec2-rds.md
  - "Plataformas e Níveis de Maturidade":
      - "Visão Geral": platforms-services/README.md
      - "Nivel 1 - Hardware e Infraestrutura": platforms-services/nivel_1.md
      - "Nivel 2 - Modelos e Serviços de ML": platforms-services/nivel_2.md
      - "Nivel 3 - Aplicacoes e Serviços de IA": platforms-services/nivel_3.md
