site_name: Aula 2 API Docs

# Tema Material para MkDocs
# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  language: en
  features:
    - navigation.expand

nav:
  - Implementation Guide:
      - Overview: index.md
      - Cost: implementation-guide/cost.md
      - Architecture overview: implementation-guide/architecture.md
      - Considerations: implementation-guide/considerations.md
      - Deployment: implementation-guide/deployment.md
      - Tutorials:
          - How to integrate Keycloak with Amazon API Gateway?: implementation-guide/tutorials/api-gateway.md
          - How to integrate Keycloak with AD/LDAP?: implementation-guide/tutorials/ad-ldap.md
      - Additional resources: implementation-guide/additional-resources.md
      - Revisions: implementation-guide/revisions.md

  - "Plataformas e Níveis de Maturidade":
      - "Visão Geral": platforms-services/README.md
      - "Nivel 1 - Hardware e Infraestrutura": platforms-services/nivel_1.md
      - "Nivel 2 - Modelos e Serviços de ML": platforms-services/nivel_2.md
      - "Nivel 3 - Aplicacoes e Serviços de IA": platforms-services/nivel_3.md
